version: '3.4'

services:

  sourcingdb:
    container_name: sourcingdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db 
      #- ./data:/data/db
    ports:
      - "27017:27017" 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  sourcingsqldb:
    container_name: sourcingsqldb
    environment:
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=admin1234 
      - POSTGRES_DB=SourcingsqlDb 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  esourcing.products:
    container_name: esourcingproduct
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
      - sourcingdb
    ports:
      - "8000:80"
    
  esourcing.sourcing:
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - sourcingdb
      - rabbitmq
    ports:
      - "8001:80"

  esourcing.order:
    container_name: esourcingorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=sourcingsqldb;Port=5432;Database=SourcingsqlDb;User Id=admin;Password=admin1234;"
      - "EventGus:HostName=rabbitmq"
    depends_on:
      - sourcingsqldb
      - rabbitmq
    ports:
      - "8002:80"


  esourcing.apigateway:
    container_name: esourcingapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - esourcing.products
      - esourcing.sourcing
      - esourcing.order
    ports:
      - "5000:80"
